import sys
import os
import requests
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Add parent directory to Python path to allow local module imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from model import Kronos, KronosTokenizer, KronosPredictor


class KronosForecaster:
    """
    Handles:
    - Fetching market data from Binance
    - Loading Kronos model
    - Preparing data
    - Running predictions
    - (Optional) plotting results
    """

    def __init__(
        self,
        symbol="BTCUSDT",
        interval="15m",
        limit=500,
        pred_len=50,
        lookback=400,
    ):
        self.symbol = symbol
        self.interval = interval
        self.limit = limit
        self.pred_len = pred_len
        self.lookback = lookback

        # Load model once (important for performance)
        self.tokenizer = KronosTokenizer.from_pretrained(
            "NeoQuasar/Kronos-Tokenizer-base"
        )
        self.model = Kronos.from_pretrained("NeoQuasar/Kronos-small")
        self.predictor = KronosPredictor(self.model, self.tokenizer, max_context=512)

    # ================================
    # Fetch Binance data
    # ================================
    def fetch_data(self):
        url = "https://api.binance.com/api/v3/klines"
        params = {
            "symbol": self.symbol,
            "interval": self.interval,
            "limit": self.limit,
        }

        response = requests.get(url, params=params)
        data = response.json()

        df = pd.DataFrame(
            data,
            columns=[
                "open_time",
                "open",
                "high",
                "low",
                "close",
                "volume",
                "close_time",
                "qav",
                "trades",
                "taker_base_vol",
                "taker_quote_vol",
                "ignore",
            ],
        )

        # Convert types
        for col in ["open", "high", "low", "close", "volume"]:
            df[col] = df[col].astype(float)

        df["timestamp"] = pd.to_datetime(df["open_time"], unit="ms")

        return df

    # ================================
    # Prepare model input
    # ================================
    def prepare_data(self, df):
        x_df = df.loc[: self.lookback - 1, ["open", "high", "low", "close", "volume"]]
        x_timestamp = df.loc[: self.lookback - 1, "timestamp"]

        last_time = df.loc[self.lookback - 1, "timestamp"]

        future_times = pd.date_range(
            start=last_time,
            periods=self.pred_len + 1,
            freq="5min",
        )[1:]

        return x_df, x_timestamp, future_times

    # ================================
    # Run prediction
    # ================================
    def predict(self):
        df = self.fetch_data()
        x_df, x_timestamp, future_times = self.prepare_data(df)

        pred_df = self.predictor.predict(
            df=x_df,
            x_timestamp=x_timestamp,
            y_timestamp=pd.Series(future_times),
            pred_len=self.pred_len,
            T=1.0,
            top_p=0.9,
            sample_count=1,
        )

        return df, pred_df

    # ================================
    # Plot results (optional)
    # ================================
    def plot(self, df, pred_df):
        # Create a new figure with a fixed size for consistent visualization
        plt.figure(figsize=(12, 6))

        # Plot historical price data (limited by lookback window)
        # This shows the real market movement used as model context
        plt.plot(
            df["timestamp"][: self.lookback],  # time axis for historical data
            df["close"][: self.lookback],      # closing prices for history
            label="History",                   # legend label for UI clarity
        )

        # Plot forecasted prices generated by the model
        # pred_df.index is assumed to represent future timestamps
        plt.plot(
            pred_df.index,          # forecast time steps (future horizon)
            pred_df["close"],       # predicted closing prices
            label="Forecast",       # legend label for predicted series
        )

        # Display legend to distinguish between history and prediction
        plt.legend()

        # Set chart title dynamically using the trading symbol
        plt.title(f"{self.symbol} Forecast")

        # Render the plot window (blocking call, not suitable for web APIs)
        plt.show()

# # ================================
# # Run as script
# # ================================
# if __name__ == "__main__":
#     forecaster = KronosForecaster()

#     df, pred_df = forecaster.predict()

#     print("\n📊 Forecast:")
#     print(pred_df.head())

#     forecaster.plot(df, pred_df)
